services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    restart: always
